### ISSUE TITLE
Update samples with final version of ML-DSA

### ISSUE THREAD

**Issue by CBonnell** [CBonnell/chameleon-certs#8]

**Comment by dghgit** [comment]
Originally emailed these, I've attempted to make the zip more spam filter friendly, hoping this gets through.

Text file contains Java program for doing generation - requires use of latest BC betas at

https://www.bouncycastle.org/betas - bcprov-*, bcutil-*, and bcpkix-*

Files should also now be using explicit tags in the extensions.

[chameleon_artifacts.zip](https://github.com/user-attachments/files/17447488/chameleon_artifacts.zip)
